# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import customers_pb2 as customers__pb2


class CustomerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/Customer/List',
                request_serializer=customers__pb2.ListRequest.SerializeToString,
                response_deserializer=customers__pb2.CustomerData.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/Customer/Retrieve',
                request_serializer=customers__pb2.CustomerRetrieveRequest.SerializeToString,
                response_deserializer=customers__pb2.CustomerData.FromString,
                )
        self.UserIdRetrieve = channel.unary_unary(
                '/Customer/UserIdRetrieve',
                request_serializer=customers__pb2.CustomerUserRetrieveRequest.SerializeToString,
                response_deserializer=customers__pb2.CustomerData.FromString,
                )
        self.Create = channel.unary_unary(
                '/Customer/Create',
                request_serializer=customers__pb2.CustomerCreateRequest.SerializeToString,
                response_deserializer=customers__pb2.CustomerData.FromString,
                )


class CustomerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserIdRetrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=customers__pb2.ListRequest.FromString,
                    response_serializer=customers__pb2.CustomerData.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=customers__pb2.CustomerRetrieveRequest.FromString,
                    response_serializer=customers__pb2.CustomerData.SerializeToString,
            ),
            'UserIdRetrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.UserIdRetrieve,
                    request_deserializer=customers__pb2.CustomerUserRetrieveRequest.FromString,
                    response_serializer=customers__pb2.CustomerData.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=customers__pb2.CustomerCreateRequest.FromString,
                    response_serializer=customers__pb2.CustomerData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Customer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Customer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Customer/List',
            customers__pb2.ListRequest.SerializeToString,
            customers__pb2.CustomerData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Customer/Retrieve',
            customers__pb2.CustomerRetrieveRequest.SerializeToString,
            customers__pb2.CustomerData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UserIdRetrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Customer/UserIdRetrieve',
            customers__pb2.CustomerUserRetrieveRequest.SerializeToString,
            customers__pb2.CustomerData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Customer/Create',
            customers__pb2.CustomerCreateRequest.SerializeToString,
            customers__pb2.CustomerData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
