# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ustomers.proto\"\r\n\x0bListRequest\".\n\x17\x43ustomerRetrieveRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x03\".\n\x1b\x43ustomerUserRetrieveRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"E\n\x15\x43ustomerCreateRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"H\n\x0c\x43ustomerData\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\x03\x12\r\n\x05\x65mail\x18\x04 \x01(\t2\xde\x01\n\x08\x43ustomer\x12\'\n\x04List\x12\x0c.ListRequest\x1a\r.CustomerData\"\x00\x30\x01\x12\x35\n\x08Retrieve\x12\x18.CustomerRetrieveRequest\x1a\r.CustomerData\"\x00\x12?\n\x0eUserIdRetrieve\x12\x1c.CustomerUserRetrieveRequest\x1a\r.CustomerData\"\x00\x12\x31\n\x06\x43reate\x12\x16.CustomerCreateRequest\x1a\r.CustomerData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LISTREQUEST']._serialized_start=19
  _globals['_LISTREQUEST']._serialized_end=32
  _globals['_CUSTOMERRETRIEVEREQUEST']._serialized_start=34
  _globals['_CUSTOMERRETRIEVEREQUEST']._serialized_end=80
  _globals['_CUSTOMERUSERRETRIEVEREQUEST']._serialized_start=82
  _globals['_CUSTOMERUSERRETRIEVEREQUEST']._serialized_end=128
  _globals['_CUSTOMERCREATEREQUEST']._serialized_start=130
  _globals['_CUSTOMERCREATEREQUEST']._serialized_end=199
  _globals['_CUSTOMERDATA']._serialized_start=201
  _globals['_CUSTOMERDATA']._serialized_end=273
  _globals['_CUSTOMER']._serialized_start=276
  _globals['_CUSTOMER']._serialized_end=498
# @@protoc_insertion_point(module_scope)
