# Generated by Django 4.1 on 2024-01-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Create by')),
                ('updated_by', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Updated by')),
                ('VisitorId', models.BigAutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('Name', models.CharField(blank=True, default='', max_length=225, null=True, verbose_name='Name')),
                ('Telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Phone Number')),
                ('Email', models.EmailField(blank=True, default='', max_length=250, null=True, verbose_name='Email Address')),
                ('SocialMediaLink', models.CharField(blank=True, default='', max_length=155, null=True, verbose_name='Social Media Link')),
                ('HighestEducation', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Highest Education')),
                ('Query', models.TextField(blank=True, null=True, verbose_name='Write Your Query')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'db_table': 'Visitor',
            },
        ),
    ]
